services:

  kopia:
    image: kopia/kopia:${KOPIA_VERSION}
    container_name: Kopia
    user: '0:0'
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - KOPIA_PASSWORD=${KOPIA_PASSWORD}
      - USER=${KOPIA_USER}
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
#      - --disable-csrf-token-checks
      - --tls-cert-file=/data/home/XXX/ssl-certs/fullchain.pem
      - --tls-key-file=/data/home/XXX/ssl-certs/privkey.pem
      - --address=${HOST_IP}:51515
      - --server-username=${SERVER_USER}
      - --server-password=${SERVER_PASSWORD}
    volumes:
      - /mnt/kopia/tmp:/tmp:shared
      - /mnt/kopia/cache:/app/cache
      - kopia_config:/app/config
      - kopia_logs:/app/logs
      - /:/data:ro
    ports:
      - 51515:51515 # WebUI
    networks:
      - moon_network

  syncthing:
    image: lscr.io/linuxserver/syncthing:${SYNCTHING_VERSION}
    hostname: syncthing
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - syncthing_config:/config
      - syncthing_data1:/data1
      - syncthing_data2:/data2
    ports:
      - 8384:8384 # WebUI
      - 22000:22000/tcp # TCP listening port
      - 22000:22000/udp # UDP listening port
      - 21027:21027/udp # Protocol discovery
    networks:
      - moon_network

volumes:
  kopia_config:
  kopia_cache:
  kopia_logs:
  syncthing_config:
  syncthing_data1:
  syncthing_data2:

networks:
  moon_network:

