services:

  kopia:
    image: kopia/kopia:${KOPIA_VERSION} # https://kopia.io/docs/installation/#docker-images
    container_name: kopia
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - KOPIA_PASSWORD=${KOPIA_PASSWORD} # repository password
      - USER=${KOPIA_USER} # repository user
    # Setup the server that provides the web ui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_SERVER_USER}
      - --server-password=${KOPIA_SERVER_PASSWORD}
    volumes:
      - ./kopia/backups:/repository # Path for storing snapshots, aka encrypted backups
      - ./kopia/snapshots:/tmp:shared # Path for browsing mounted snaphots
      # Local folders needed by kopia
      - ./kopia/config:/app/config
      - ./kopia/cache:/app/cache
      - ./kopia/logs:/app/logs
    ports:
      - 51515:51515 # WebUI
    networks:
      - moon_network

  syncthing:
    image: lscr.io/linuxserver/syncthing:${SYNCTHING_VERSION}
    hostname: syncthing
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./syncthing/config:/config
      - ./syncthing/data1:/data1
      - ./syncthing/data2:/data2
    ports:
      - 8384:8384 # WebUI
      - 22000:22000/tcp # TCP listening port
      - 22000:22000/udp # UDP listening port
      - 21027:21027/udp # Protocol discovery
    networks:
      - moon_network
      
networks:
  moon_network:

