services:

vorta:
    image: ghcr.io/borgbase/vorta-docker:${VORTA_VERSION} # https://github.com/borgbase/vorta-docker
    container_name: vorta
    hostname: vorta
    restart: unless-stopped
#    cap_add:
#      - SYS_ADMIN
#    security_opt:
#      - apparmor:unconfined
#    privileged: true
    environment:
      - USER_ID=${UID}
      - GROUP_ID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./vorta/config:/config
      - ./vorta/backups:/destination
    ports:
      - 5811:5800

  kopia:
    image: kopia/kopia:${KOPIA_VERSION} # https://kopia.io/docs/installation/#docker-images
    container_name: kopia
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - USER=${KOPIA_USER} # repository user
      - KOPIA_PASSWORD=${KOPIA_PASSWORD} # repository password
    # Setup the server that provides the web ui
    command:
      - server
      - start
#      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --tls-key-file=/tls/kopia-key.pem
      - --tls-cert-file=/tls/kopia-cert.pem
      - --server-username=${KOPIA_USER}
      - --server-password=${KOPIA_PASSWORD}
    volumes:
      - ./kopia/backups:/repository # Path for storing snapshots, aka encrypted backups
      - ./kopia/snapshots:/tmp:shared # Path for browsing mounted snaphots
      # Local folders needed by kopia
      - ./kopia/config:/app/config
      - ./kopia/cache:/app/cache
      - ./kopia/logs:/app/logs
      # TLS private key and cert path. Both key and cert must be generated via openssl on host BEFORE bringing up containers. 
      - ./kopia/tls:/tls
    ports:
      - 51515:51515 # WebUI
    networks:
      - moon_network

  syncthing:
    image: lscr.io/linuxserver/syncthing:${SYNCTHING_VERSION}
    container_name: syncthing
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./syncthing/config:/config
      - ./syncthing/backups:/backups
    ports:
      - 8384:8384 # WebUI
      - 22000:22000/tcp # TCP listening port
      - 22000:22000/udp # UDP listening port
      - 21027:21027/udp # Protocol discovery
    networks:
      - moon_network
      
networks:
  moon_network:

