global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml
  
scrape_configs:
  - job_name: node
    static_configs:
      - targets:
        - prometheus:9090
        - idonotexist:564


