---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt.builtin.apt:
      update_cache: yes

  - name: install apache2 package
    apt.builtin.apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt.builtin.apt:
      name: libapache2-mod-php
      state: latest
