services:

  ###### ----- Network ----- ######

  gluetun:
    image: qmcgaw/gluetun:${GLUETUN_VERSION}
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER} # mullvad setup: https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS} # 10.68.243.38/32 for mullvad
      - OWNED_ONLY=yes # If the vpn server is owned by mullvad. default is no, which includes all servers
      - TZ=${TIMEZONE}
      - UPDATER_PERIOD=24h # Server list updater, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 8000:8000 # gluetun HTTP control server / web UI
      - 8085:8085 # qbitorrent web ui
      - 6881:6881 # qbittorrent incoming connections port (downloads/uploads)
      - 6881:6881/udp # qbittorrent UDP incoming connections port
      - 8080:8080 # sabnzbd web ui. check sabnzbd.ini if running into issues. may be 8085 by default?
      - 563:563/tcp # sabnzbd SSL News Transfer Protocol port
      - 119:119/tcp # sabnzbd News Transfer Protocol port
      - 8989:8989 # sonarr web ui
      - 7878:7878 # radarr web ui
      - 8686:8686 # lidarr web ui
      - 8787:8787 # readarr web ui
      - 9696:9696 # prowlarr web ui
      - 6767:6767 # bazarr web ui
      - 8191:8191 # flaresolverr

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    depends_on:
      gluetun:
        condition: service_healthy

  qbittorrent: # https://docs.linuxserver.io/images/docker-qbittorrent/
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8085
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest # optional custom web ui. Must enable alternate web ui in qbittorrent options and point file location to /vuetorrent 
    volumes:
      - ./qbittorrent/config:/config
      - ${TORRENTS_PATH}:/nebula-downloads/torrents:rw
    depends_on:
      gluetun:
        condition: service_healthy

  sabnzbd: # https://docs.linuxserver.io/images/docker-sabnzbd/#usage
    image: lscr.io/linuxserver/sabnzbd:${SABNZBD_VERSION}
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sabnzbd/config:/config
      - ${USENET_PATH}:/nebula-downloads/usenet:rw
    depends_on:
      gluetun:
        condition: service_healthy

  ###### ----- Media Management ----- ######

  sonarr: # https://docs.linuxserver.io/images/docker-sonarr/?h=sonarr
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr/config:/config
      - ${DOWNLOADS_PATH}:/nebula-downloads
      - ${SERIES_PATH}:/nebula-media/series
    depends_on:
      gluetun:
        condition: service_healthy

  radarr: # https://docs.linuxserver.io/images/docker-radarr/#media-folders
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr/config:/config
      - ${DOWNLOADS_PATH}:/nebula-downloads
      - ${MOVIES_PATH}:/nebula-media/movies
    depends_on:
      gluetun:
        condition: service_healthy

  lidarr: # https://docs.linuxserver.io/images/docker-lidarr/#media-folders
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./lidarr/config:/config
      - ${DOWNLOADS_PATH}:/nebula-downloads
      - ${MUSIC_PATH}:/nebula-media/music
    depends_on:
      gluetun:
        condition: service_healthy

  readarr:
    image: lscr.io/linuxserver/readarr:${READARR_VERSION}
    container_name: readarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./readarr/config:/config
      - ${DOWNLOADS_PATH}:/nebula-downloads
      - ${BOOKS_PATH}:/mebula-media/books
    depends_on:
      gluetun:
        condition: service_healthy

  prowlarr: # https://docs.linuxserver.io/images/docker-prowlarr/
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION}
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./prowlarr/config:/config
      - ${MEDIA_ROOT_PATH}:/nebula-media
    depends_on:
      gluetun:
        condition: service_healthy

  bazarr:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION}
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr/config:/config
      - ${MOVIES_PATH}:/nebula-media/movies
      - ${SERIES_PATH}:/nebula-media/series
    depends_on:
      gluetun:
        condition: service_healthy

