services:

# ============================================================== #
# docker-wireguard-pia: https://github.com/thrnz/docker-wireguard-pia
# ============================================================== #

  vpn:
    image: thrnz/docker-wireguard-pia:${VPN_VERS:-latest}
    container_name: docker-wireguard-pia
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    environment:
      - LOCAL_NETWORK=10.0.0.0/8
      - LOC=swiss
      - USER=${PIA_USER}
      - PASS=${PIA_PASSWORD}
      - VPNDNS=${VPNDNS}
      - PORT_FORWARDING=1
      - PORT_PERSIST=1 # Set to 1 to attempt to keep the same port forwarded when the container is restarted.
      - PORT_FILE=/pia-shared/forwarded_port.txt # The forwarded port number is dumped here for possible access by scripts in other containers. By default this is /pia-shared/port.dat.
      - KEEPALIVE=25 # This can be used to ensure incoming packets on an idle link aren't lost when behind NAT.
    volumes:
      - /home/xo/docker/pia:/pia # Auth token is stored here
      - /home/xo/docker/pia/shared:/pia-shared # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
    ports:
      - 8090:8080 # qbitorrent web ui
      - 8989:8989 # sonarr web ui
      - 7878:7878 # radarr web ui
      - 9696:9696 # prowlarr web ui
      - 6767:6767 # bazarr web ui
      - 8191:8191 # flaresolverr

# ============================================================== #
# qb-port: # https://hub.docker.com/r/charlocharlie/qbittorrent-port-forward-file
# ============================================================== #

  qb-port:
    image: charlocharlie/qbittorrent-port-forward-file:${QBPORT_VERS:-latest}
    container_name: qb-port
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    network_mode: "service:vpn"
    environment:
      - QBT_USERNAME:${QBT_USERNAME} # I could not get authentication to work properly without "bypassing authentication for clients on
      - QBT_PASSWORD:${QBT_PASSWORD} # localhost" in qb settings, and i suspect it is due to the vuetorrent alternate web UI.
      - QBT_ADDR:${QBT_ADDR}
      - PORT_FILE:/config/forwarded_port.txt
    volumes:
      - /home/xo/docker/pia/shared:/config:ro

# ============================================================== #
# seedboxapi:
# ============================================================== #

  seedboxapi:
    image: myanonamouse/seedboxapi
    container_name: seedboxapi
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    user: ${UID}:${GID}
    network_mode: "service:vpn"
    environment:
      - mam_id=${MAM_ID}
      - interval=1
      - DEBUG=1
    volumes:
      - /home/xo/docker/seedboxapi:/config # may need to adjust permissions if encountering file creation error: sudo chown -R 3000:3000 /home/xo/seedboxapi

# ============================================================== #
# flaresolverr:
# ============================================================== #

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# qbittorrent: # https://docs.linuxserver.io/images/docker-qbittorrent/
# ============================================================== #

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - /home/xo/docker/qbittorrent/config:/config
      - /mnt/seedpool:/seedpool:rw
      - /mnt/coldpool:/cooldpool:rw
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# qui: https://getqui.com/docs/getting-started/docker
# ============================================================== #

  qui:
    image: ghcr.io/autobrr/qui:${QUI_VERSION}
    container_name: qui
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    environment: # https://getqui.com/docs/configuration/environment
      - PUID=${UID}
      - PGID=${GID}
      - QUI__METRICS_ENABLED=true # enable prometheus metrics
    volumes:
      - /home/xo/docker/qui:/config
      - /mnt/seedpool:/seedpool:rw
      - /mnt/coldpool:/cooldpool:rw
    ports:
      - "7476:7476"
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# sonarr: # https://docs.linuxserver.io/images/docker-sonarr/?h=sonarr
# ============================================================== #

  sonarr:
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/xo/docker/sonarr/config:/config
      - /mnt/series:/series
      - /mnt/seedpool:/seedpool
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# radarr: # https://docs.linuxserver.kalen_qbittorrentio/images/docker-radarr/#media-folders
# ============================================================== #

  radarr: # https://docs.linuxserver.io/images/docker-radarr/#media-folders
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/xo/docker/radarr/config:/config
      - /mnt/movies:/movies
      - /mnt/seedpool:/seedpool
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# prowlarr: # https://docs.linuxserver.io/images/docker-prowlarr/
# ============================================================== #

  prowlarr: # https://docs.linuxserver.io/images/docker-prowlarr/
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION}
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/xo/docker/prowlarr/config:/config
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #
# bazarr:
# ============================================================== #

  bazarr:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION}
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    network_mode: "service:vpn"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/xo/docker/bazarr/config:/config
      - /mnt/movies:/movies
      - /mnt/series:/series
    depends_on:
      vpn:
        condition: service_healthy

# ============================================================== #

#volumes:
  #example-volume

#networks:
  #example_net:
