services:

# -----------------------------------------------------------------
# Audiobookshelf: https://www.audiobookshelf.org/docs/#docker-compose-install
# -----------------------------------------------------------------

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:${ABS_VERS:-latest}
    container_name: audiobookshelf
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    env_file: hyperion.env
    environment:
      - AUDIOBOOKSHELF_UID=${UID}
      - AUDIOBOOKSHELF_GID=${GID}
    volumes:
      - ${ABS_ROOT_DIR}:/books
      - ./audiobookshelf/metadata:/metadata
      - ./audiobookshelf/config:/config
    ports:
      - 13378:80
    networks:
      audiobookshelf_net:

# -----------------------------------------------------------------
# Linkwarden: https://docs.linkwarden.app/self-hosting/installation
# -----------------------------------------------------------------

  postgres:
    image: postgres:16-alpine
    container_name: linkwarden_db
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    env_file: hyperion.env
    volumes:
      - ./linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      linkwarden_net:

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    env_file: hyperion.env
    environment:
      # DATABASE_URL = engine://username:password@host:port/dbname.
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    volumes:
      - ./linkwarden/data:/data/data
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      linkwarden_net:

# ---------------------------------------------
# ConvertX: https://github.com/C4illin/ConvertX
# ---------------------------------------------

  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    env_file: hyperion.env
    environment:
      - JWT_SECRET=${CONVERTX_JWT_SECRET} # will use randomUUID() if unset
      - HTTP_ALLOWED=false
      - ALLOW_UNAUTHENTICATED=false
      - AUTO_DELETE_EVERY_N_HOURS=24
      - ACCOUNT_REGISTRATION=false
    volumes:
      - ./convertx/data:/app/data
    ports:
      - 3003:3000
    networks:
      convertx_net:

# ---------------------------------------------

networks:
  linkwarden_net:
    driver: bridge
  convertx_net:
    driver: bridge
