services:

  linkding:
    container_name: "${LINKD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:"${LINKD_VERS:-latest-alpine}" # https://hub.docker.com/r/sissbruecker/linkding/tags
    security_opt:
      - no-new-privileges:true
      - cap_drop=ALL
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    user: "3000:3000"
    env_file:
      - hyperion.env
    volumes:
      - "${LINKD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    ports:
      - "${LINKD_HOST_PORT:-9090}:9090"
    networks:
      hyperion_net:

    
#-------------------------#
#-------- Tandoor --------#
#-------------------------#

  db_recipes:
    image: postgres:16-alpine
    container_name: tandoor-db
    security_opt:
      - no-new-privileges:true
      - cap_drop=ALL
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    user: "3000:3000"
    env_file:
      - hyperion.env
    volumes:
      - ./tandoor/postgresql:/var/lib/postgresql/data
    networks:
      hyperion_net:

  web_recipes:
    image: vabene1111/recipes
    container_name: tandoor
    security_opt:
      - no-new-privileges:true
      - cap_drop=ALL
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    user: "3000:3000"
    env_file:
      - hyperion.env
    volumes:
      - ./tandoor/recipes:/opt/recipes/staticfiles
      - ./tandoor/mediafiles:/opt/recipes/mediafiles
      - nginx_config:/opt/recipes/nginx/conf.d # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
    depends_on:
      - db_recipes
    networks:
      hyperion_net:

  nginx_recipes:
    image: nginx:mainline-alpine
    container_name: tandoor-nginx
    security_opt:
      - no-new-privileges:true
      - cap_drop=ALL
    restart: unless-stopped
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    user: "3000:3000"
    env_file:
      - hyperion.env
    volumes:
      - ./tandoor/staticfiles:/static:ro
      - ./tandoor/mediafiles:/media:ro
      - nginx_config:/etc/nginx/conf.d:ro # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
    depends_on:
      - web_recipes
    ports:
      - 8086:80
    networks:
      hyperion_net:
      
networks:
  hyperion_net:

volumes:
  nginx_config:
