services:

# ============================================================== #
# Uptime Kuma: https://github.com/louislam/uptime-kuma/blob/1.23.X/docker/docker-compose.yml
# ============================================================== #

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      - PUID=3000
      - GUID=3000
      - TZ=America/Denver
    volumes:
      - ./uptime-kuma/data:/app/data
    ports:
      - 3001:3001 # WebUI
    networks:
      exoplanet-net:

# ============================================================== #
# Homepage: https://gethomepage.dev/installation/docker/
# ============================================================== #

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
      - HOMEPAGE_ALLOWED_HOSTS=home.kalen.io
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    ports:
      - 3000:3000
    networks:
      exoplanet-net:

# ============================================================== #
# Caddy: https://hub.docker.com/_/caddy/
# ============================================================== #

  caddy:
    image: caddy:alpine
    container_name: caddy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - 80:80 # http
      - 443:443 # https
      - 2019:2019 # admin endpoint
    networks:
      exoplanet-net:

# ============================================================== #

networks:
  exoplanet-net:
    driver: bridge
