services:

# ============================================================== #
# Uptime Kuma: https://github.com/louislam/uptime-kuma/blob/1.23.X/docker/docker-compose.yml
# ============================================================== #

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      - PUID=3000
      - GUID=3000
      - TZ=America/Denver
    volumes:
      - ./uptime-kuma/data:/app/data
    ports:
      - 127.0.0.1:3001:3001 # WebUI access for localhost to allow for healthchecks.io ping script
    networks:
      exoplanet-net:

# ============================================================== #
# Homepage: https://gethomepage.dev/installation/docker/
# ============================================================== #

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
      - HOMEPAGE_ALLOWED_HOSTS=home.kalen.io
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    ports:
      - 3000:3000
    networks:
      exoplanet-net:

# ============================================================== #
# Caddy: https://hub.docker.com/_/caddy/
# ============================================================== #

  caddy:
    build: .
    image: caddy-custom:latest
    container_name: caddy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - 80:80 # http
      - 443:443 # https
      - 2019:2019 # admin endpoint
    networks:
      exoplanet-net:

# ============================================================== #
# ntfy: 
# ============================================================== #

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    command:
      - serve
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          'CMD-SHELL',
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy/data:/etc/ntfy
    ports:
      - 8000:80
    networks:
      exoplanet-net:

# ============================================================== 

networks:
  exoplanet-net:
    driver: bridge
